[package]
name = "hotas-panel-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-xinput = "1.2.0"
serialport = "4.2.0"
vigem-client = "0.1.4"
winapi = "0.3.9"
